In [1]:
import os 
path="F:\Online IT learning\Python learning\Daily 30mn Python learning\Pandas"
os.chdir(path)

In [2]:
import numpy as np
import pandas as pd
%matplotlib inline

In [5]:
df= pd.read_csv("WHO-COVID-19-global-data.csv")
df

,Date_reported,Country_code,Country,WHO_region,New_cases,Cumulative_cases,New_deaths,Cumulative_deaths
0,2020-01-03,AF,Afghanistan,EMRO,0,0,0,0
1,2020-01-04,AF,Afghanistan,EMRO,0,0,0,0
2,2020-01-05,AF,Afghanistan,EMRO,0,0,0,0
3,2020-01-06,AF,Afghanistan,EMRO,0,0,0,0
4,2020-01-07,AF,Afghanistan,EMRO,0,0,0,0
5,2020-01-08,AF,Afghanistan,EMRO,0,0,0,0
6,2020-01-09,AF,Afghanistan,EMRO,0,0,0,0
7,2020-01-10,AF,Afghanistan,EMRO,0,0,0,0
8,2020-01-11,AF,Afghanistan,EMRO,0,0,0,0
9,2020-01-12,AF,Afghanistan,EMRO,0,0,0,0
10,2020-01-13,AF,Afghanistan,EMRO,0,0,0,0
11,2020-01-14,AF,Afghanistan,EMRO,0,0,0,0
12,2020-01-15,AF,Afghanistan,EMRO,0,0,0,0
13,2020-01-16,AF,Afghanistan,EMRO,0,0,0,0
14,2020-01-17,AF,Afghanistan,EMRO,0,0,0,0
15,2020-01-18,AF,Afghanistan,EMRO,0,0,0,0
16,2020-01-19,AF,Afghanistan,EMRO,0,0,0,0
17,2020-01-20,AF,Afghanistan,EMRO,0,0,0,0
18,2020-01-21,AF,Afghanistan,EMRO,0,0,0,0
19,2020-01-22,AF,Afghanistan,EMRO,0,0,0,0
20,2020-01-23,AF,Afghanistan,EMRO,0,0,0,0
21,2020-01-24,AF,Afghanistan,EMRO,0,0,0,0
22,2020-01-25,AF,Afghanistan,EMRO,0,0,0,0
23,2020-01-26,AF,Afghanistan,EMRO,0,0,0,0
24,2020-01-27,AF,Afghanistan,EMRO,0,0,0,0
25,2020-01-28,AF,Afghanistan,EMRO,0,0,0,0
26,2020-01-29,AF,Afghanistan,EMRO,0,0,0,0
27,2020-01-30,AF,Afghanistan,EMRO,0,0,0,0
28,2020-01-31,AF,Afghanistan,EMRO,0,0,0,0
29,2020-02-01,AF,Afghanistan,EMRO,0,0,0,0
...,...,...,...,...,...,...,...,...
86238,2020-12-02,ZW,Zimbabwe,AFRO,95,10129,0,277
86239,2020-12-03,ZW,Zimbabwe,AFRO,114,10243,0,277
86240,2020-12-04,ZW,Zimbabwe,AFRO,181,10424,3,280
86241,2020-12-05,ZW,Zimbabwe,AFRO,123,10547,1,281
86242,2020-12-06,ZW,Zimbabwe,AFRO,70,10617,10,291
86243,2020-12-07,ZW,Zimbabwe,AFRO,101,10718,0,291
86244,2020-12-08,ZW,Zimbabwe,AFRO,121,10839,3,294
86245,2020-12-09,ZW,Zimbabwe,AFRO,0,10839,0,294
86246,2020-12-10,ZW,Zimbabwe,AFRO,168,11007,10,304
86247,2020-12-11,ZW,Zimbabwe,AFRO,74,11081,1,305
86248,2020-12-12,ZW,Zimbabwe,AFRO,0,11081,0,305
86249,2020-12-13,ZW,Zimbabwe,AFRO,0,11081,0,305
86250,2020-12-14,ZW,Zimbabwe,AFRO,165,11246,2,307
86251,2020-12-15,ZW,Zimbabwe,AFRO,112,11358,2,309
86252,2020-12-16,ZW,Zimbabwe,AFRO,164,11522,1,310
86253,2020-12-17,ZW,Zimbabwe,AFRO,0,11522,0,310
86254,2020-12-18,ZW,Zimbabwe,AFRO,344,11866,4,314
86255,2020-12-19,ZW,Zimbabwe,AFRO,181,12047,2,316
86256,2020-12-20,ZW,Zimbabwe,AFRO,104,12151,2,318
86257,2020-12-21,ZW,Zimbabwe,AFRO,174,12325,2,320
86258,2020-12-22,ZW,Zimbabwe,AFRO,97,12422,2,322
86259,2020-12-23,ZW,Zimbabwe,AFRO,122,12544,4,326
86260,2020-12-24,ZW,Zimbabwe,AFRO,0,12544,0,326
86261,2020-12-25,ZW,Zimbabwe,AFRO,242,12786,13,339
86262,2020-12-26,ZW,Zimbabwe,AFRO,94,12880,2,341
86263,2020-12-27,ZW,Zimbabwe,AFRO,83,12963,0,341
86264,2020-12-28,ZW,Zimbabwe,AFRO,0,12963,0,341
86265,2020-12-29,ZW,Zimbabwe,AFRO,185,13148,13,354
86266,2020-12-30,ZW,Zimbabwe,AFRO,0,13148,0,354
86267,2020-12-31,ZW,Zimbabwe,AFRO,477,13625,6,360

In [31]:
df_index=df.index
df_index

RangeIndex(start=0, stop=86268, step=1)

In [33]:
df_cols=df.columns
df_cols

Index(['Date_reported', 'Country_code', 'Country', 'WHO_region', 'New_cases',
       'Cumulative_cases', 'New_deaths', 'Cumulative_deaths'],
      dtype='object')

In [34]:
df_index.values

array([    0,     1,     2, ..., 86265, 86266, 86267], dtype=int64)

In [35]:
df.values

array([['2020-01-03', 'AF', 'Afghanistan', ..., 0, 0, 0],
       ['2020-01-04', 'AF', 'Afghanistan', ..., 0, 0, 0],
       ['2020-01-05', 'AF', 'Afghanistan', ..., 0, 0, 0],
       ...,
       ['2020-12-29', 'ZW', 'Zimbabwe', ..., 13148, 13, 354],
       ['2020-12-30', 'ZW', 'Zimbabwe', ..., 13148, 0, 354],
       ['2020-12-31', 'ZW', 'Zimbabwe', ..., 13625, 6, 360]], dtype=object)

In [36]:
df.dtypes

Date_reported        object
Country_code         object
Country              object
WHO_region           object
New_cases             int64
Cumulative_cases      int64
New_deaths            int64
Cumulative_deaths     int64
dtype: object

In [37]:
df.shape

(86268, 8)

In [38]:
df.head()

,Date_reported,Country_code,Country,WHO_region,New_cases,Cumulative_cases,New_deaths,Cumulative_deaths
0,2020-01-03,AF,Afghanistan,EMRO,0,0,0,0
1,2020-01-04,AF,Afghanistan,EMRO,0,0,0,0
2,2020-01-05,AF,Afghanistan,EMRO,0,0,0,0
3,2020-01-06,AF,Afghanistan,EMRO,0,0,0,0
4,2020-01-07,AF,Afghanistan,EMRO,0,0,0,0

In [39]:
df.tail()

,Date_reported,Country_code,Country,WHO_region,New_cases,Cumulative_cases,New_deaths,Cumulative_deaths
86263,2020-12-27,ZW,Zimbabwe,AFRO,83,12963,0,341
86264,2020-12-28,ZW,Zimbabwe,AFRO,0,12963,0,341
86265,2020-12-29,ZW,Zimbabwe,AFRO,185,13148,13,354
86266,2020-12-30,ZW,Zimbabwe,AFRO,0,13148,0,354
86267,2020-12-31,ZW,Zimbabwe,AFRO,477,13625,6,360

In [40]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 86268 entries, 0 to 86267
Data columns (total 8 columns):
Date_reported        86268 non-null object
Country_code         85904 non-null object
Country              86268 non-null object
WHO_region           86268 non-null object
New_cases            86268 non-null int64
Cumulative_cases     86268 non-null int64
New_deaths           86268 non-null int64
Cumulative_deaths    86268 non-null int64
dtypes: int64(4), object(4)
memory usage: 5.3+ MB

In [41]:
df.describe()

           New_cases  Cumulative_cases    New_deaths  Cumulative_deaths
count   86268.000000      8.626800e+04  86268.000000       86268.000000
mean      944.441195      8.684401e+04     20.842607        2559.126884
std      6494.096255      6.006321e+05    119.731790       14537.679404
min    -32952.000000      0.000000e+00   -514.000000           0.000000
25%         0.000000      2.000000e+00      0.000000           0.000000
50%         2.000000      5.570000e+02      0.000000          10.000000
75%       127.000000      1.169100e+04      2.000000         221.000000
max    402270.000000      1.934679e+07   6409.000000      335789.000000

In [45]:
df["Country"]

0        Afghanistan
1        Afghanistan
2        Afghanistan
3        Afghanistan
4        Afghanistan
5        Afghanistan
6        Afghanistan
7        Afghanistan
8        Afghanistan
9        Afghanistan
10       Afghanistan
11       Afghanistan
12       Afghanistan
13       Afghanistan
14       Afghanistan
15       Afghanistan
16       Afghanistan
17       Afghanistan
18       Afghanistan
19       Afghanistan
20       Afghanistan
21       Afghanistan
22       Afghanistan
23       Afghanistan
24       Afghanistan
25       Afghanistan
26       Afghanistan
27       Afghanistan
28       Afghanistan
29       Afghanistan
            ...
86238       Zimbabwe
86239       Zimbabwe
86240       Zimbabwe
86241       Zimbabwe
86242       Zimbabwe
86243       Zimbabwe
86244       Zimbabwe
86245       Zimbabwe
86246       Zimbabwe
86247       Zimbabwe
86248       Zimbabwe
86249       Zimbabwe
86250       Zimbabwe
86251       Zimbabwe
86252       Zimbabwe
86253       Zimbabwe
86254       Zimbabwe
86255       Zimbabwe
86256       Zimbabwe
86257       Zimbabwe
86258       Zimbabwe
86259       Zimbabwe
86260       Zimbabwe
86261       Zimbabwe
86262       Zimbabwe
86263       Zimbabwe
86264       Zimbabwe
86265       Zimbabwe
86266       Zimbabwe
86267       Zimbabwe
Name: Country, Length: 86268, dtype: object

In [47]:
df["Country"].unique()

array(['Afghanistan', 'Albania', 'Algeria', 'American Samoa', 'Andorra',
       'Angola', 'Anguilla', 'Antigua and Barbuda', 'Argentina',
       'Armenia', 'Aruba', 'Australia', 'Austria', 'Azerbaijan',
       'Bahamas', 'Bahrain', 'Bangladesh', 'Barbados', 'Belarus',
       'Belgium', 'Belize', 'Benin', 'Bermuda', 'Bhutan',
       'Bolivia (Plurinational State of)', 'Bonaire',
       'Bosnia and Herzegovina', 'Botswana', 'Brazil',
       'British Virgin Islands', 'Brunei Darussalam', 'Bulgaria',
       'Burkina Faso', 'Burundi', 'Cabo Verde', 'Cambodia', 'Cameroon',
       'Canada', 'Cayman Islands', 'Central African Republic', 'Chad',
       'Chile', 'China', 'Colombia', 'Comoros', 'Congo', 'Cook Islands',
       'Costa Rica', 'Côte d’Ivoire', 'Croatia', 'Cuba', 'Curaçao',
       'Cyprus', 'Czechia', "Democratic People's Republic of Korea",
       'Democratic Republic of the Congo', 'Denmark', 'Djibouti',
       'Dominica', 'Dominican Republic', 'Ecuador', 'Egypt',
       'El Salvador', 'Equatorial Guinea', 'Eritrea', 'Estonia',
       'Eswatini', 'Ethiopia', 'Falkland Islands (Malvinas)',
       'Faroe Islands', 'Fiji', 'Finland', 'France', 'French Guiana',
       'French Polynesia', 'Gabon', 'Gambia', 'Georgia', 'Germany',
       'Ghana', 'Gibraltar', 'Greece', 'Greenland', 'Grenada',
       'Guadeloupe', 'Guam', 'Guatemala', 'Guernsey', 'Guinea',
       'Guinea-Bissau', 'Guyana', 'Haiti', 'Holy See', 'Honduras',
       'Hungary', 'Iceland', 'India', 'Indonesia',
       'Iran (Islamic Republic of)', 'Iraq', 'Ireland', 'Isle of Man',
       'Israel', 'Italy', 'Jamaica', 'Japan', 'Jersey', 'Jordan',
       'Kazakhstan', 'Kenya', 'Kiribati', 'Kosovo[1]', 'Kuwait',
       'Kyrgyzstan', "Lao People's Democratic Republic", 'Latvia',
       'Lebanon', 'Lesotho', 'Liberia', 'Libya', 'Liechtenstein',
       'Lithuania', 'Luxembourg', 'Madagascar', 'Malawi', 'Malaysia',
       'Maldives', 'Mali', 'Malta', 'Marshall Islands', 'Martinique',
       'Mauritania', 'Mauritius', 'Mayotte', 'Mexico',
       'Micronesia (Federated States of)', 'Monaco', 'Mongolia',
       'Montenegro', 'Montserrat', 'Morocco', 'Mozambique', 'Myanmar',
       'Namibia', 'Nauru', 'Nepal', 'Netherlands', 'New Caledonia',
       'New Zealand', 'Nicaragua', 'Niger', 'Nigeria', 'Niue',
       'North Macedonia',
       'Northern Mariana Islands (Commonwealth of the)', 'Norway',
       'occupied Palestinian territory, including east Jerusalem', 'Oman',
       'Other', 'Pakistan', 'Palau', 'Panama', 'Papua New Guinea',
       'Paraguay', 'Peru', 'Philippines', 'Pitcairn Islands', 'Poland',
       'Portugal', 'Puerto Rico', 'Qatar', 'Republic of Korea',
       'Republic of Moldova', 'Réunion', 'Romania', 'Russian Federation',
       'Rwanda', 'Saba', 'Saint Barthélemy', 'Saint Helena',
       'Saint Kitts and Nevis', 'Saint Lucia', 'Saint Martin',
       'Saint Pierre and Miquelon', 'Saint Vincent and the Grenadines',
       'Samoa', 'San Marino', 'Sao Tome and Principe', 'Saudi Arabia',
       'Senegal', 'Serbia', 'Seychelles', 'Sierra Leone', 'Singapore',
       'Sint Eustatius', 'Sint Maarten', 'Slovakia', 'Slovenia',
       'Solomon Islands', 'Somalia', 'South Africa', 'South Sudan',
       'Spain', 'Sri Lanka', 'Sudan', 'Suriname', 'Sweden', 'Switzerland',
       'Syrian Arab Republic', 'Tajikistan', 'Thailand',
       'The United Kingdom', 'Timor-Leste', 'Togo', 'Tokelau', 'Tonga',
       'Trinidad and Tobago', 'Tunisia', 'Turkey', 'Turkmenistan',
       'Turks and Caicos Islands', 'Tuvalu', 'Uganda', 'Ukraine',
       'United Arab Emirates', 'United Republic of Tanzania',
       'United States of America', 'United States Virgin Islands',
       'Uruguay', 'Uzbekistan', 'Vanuatu',
       'Venezuela (Bolivarian Republic of)', 'Viet Nam',
       'Wallis and Futuna', 'Yemen', 'Zambia', 'Zimbabwe'], dtype=object)

In [6]:
df.columns=[col.strip() for col in df.columns]
df.columns

Index(['Date_reported', 'Country_code', 'Country', 'WHO_region', 'New_cases',
       'Cumulative_cases', 'New_deaths', 'Cumulative_deaths'],
      dtype='object')

In [7]:
df.Country

0        Afghanistan
1        Afghanistan
2        Afghanistan
3        Afghanistan
4        Afghanistan
5        Afghanistan
6        Afghanistan
7        Afghanistan
8        Afghanistan
9        Afghanistan
10       Afghanistan
11       Afghanistan
12       Afghanistan
13       Afghanistan
14       Afghanistan
15       Afghanistan
16       Afghanistan
17       Afghanistan
18       Afghanistan
19       Afghanistan
20       Afghanistan
21       Afghanistan
22       Afghanistan
23       Afghanistan
24       Afghanistan
25       Afghanistan
26       Afghanistan
27       Afghanistan
28       Afghanistan
29       Afghanistan
            ...
86238       Zimbabwe
86239       Zimbabwe
86240       Zimbabwe
86241       Zimbabwe
86242       Zimbabwe
86243       Zimbabwe
86244       Zimbabwe
86245       Zimbabwe
86246       Zimbabwe
86247       Zimbabwe
86248       Zimbabwe
86249       Zimbabwe
86250       Zimbabwe
86251       Zimbabwe
86252       Zimbabwe
86253       Zimbabwe
86254       Zimbabwe
86255       Zimbabwe
86256       Zimbabwe
86257       Zimbabwe
86258       Zimbabwe
86259       Zimbabwe
86260       Zimbabwe
86261       Zimbabwe
86262       Zimbabwe
86263       Zimbabwe
86264       Zimbabwe
86265       Zimbabwe
86266       Zimbabwe
86267       Zimbabwe
Name: Country, Length: 86268, dtype: object

In [9]:
#kivabe ekta selected raw  k dekhano jay (loc information ja ami dekhte chai tar modde level dite use hoy)
df.loc[1:4,"Country"]
df.loc[1:8, ["Country", "New_cases"]]

       Country  New_cases
1  Afghanistan          0
2  Afghanistan          0
3  Afghanistan          0
4  Afghanistan          0
5  Afghanistan          0
6  Afghanistan          0
7  Afghanistan          0
8  Afghanistan          0

In [10]:
df.Country=="United States of America"

0        False
1        False
2        False
3        False
4        False
5        False
6        False
7        False
8        False
9        False
10       False
11       False
12       False
13       False
14       False
15       False
16       False
17       False
18       False
19       False
20       False
21       False
22       False
23       False
24       False
25       False
26       False
27       False
28       False
29       False
         ...
86238    False
86239    False
86240    False
86241    False
86242    False
86243    False
86244    False
86245    False
86246    False
86247    False
86248    False
86249    False
86250    False
86251    False
86252    False
86253    False
86254    False
86255    False
86256    False
86257    False
86258    False
86259    False
86260    False
86261    False
86262    False
86263    False
86264    False
86265    False
86266    False
86267    False
Name: Country, Length: 86268, dtype: bool

In [11]:
df[df.Country=="United States of America"]

,Date_reported,Country_code,Country,WHO_region,New_cases,Cumulative_cases,New_deaths,Cumulative_deaths
82264,2020-01-03,US,United States of America,AMRO,0,0,0,0
82265,2020-01-04,US,United States of America,AMRO,0,0,0,0
82266,2020-01-05,US,United States of America,AMRO,0,0,0,0
82267,2020-01-06,US,United States of America,AMRO,0,0,0,0
82268,2020-01-07,US,United States of America,AMRO,0,0,0,0
82269,2020-01-08,US,United States of America,AMRO,0,0,0,0
82270,2020-01-09,US,United States of America,AMRO,0,0,0,0
82271,2020-01-10,US,United States of America,AMRO,0,0,0,0
82272,2020-01-11,US,United States of America,AMRO,0,0,0,0
82273,2020-01-12,US,United States of America,AMRO,0,0,0,0
82274,2020-01-13,US,United States of America,AMRO,0,0,0,0
82275,2020-01-14,US,United States of America,AMRO,0,0,0,0
82276,2020-01-15,US,United States of America,AMRO,0,0,0,0
82277,2020-01-16,US,United States of America,AMRO,0,0,0,0
82278,2020-01-17,US,United States of America,AMRO,0,0,0,0
82279,2020-01-18,US,United States of America,AMRO,0,0,0,0
82280,2020-01-19,US,United States of America,AMRO,0,0,0,0
82281,2020-01-20,US,United States of America,AMRO,5,5,0,0
82282,2020-01-21,US,United States of America,AMRO,0,5,0,0
82283,2020-01-22,US,United States of America,AMRO,0,5,0,0
82284,2020-01-23,US,United States of America,AMRO,0,5,0,0
82285,2020-01-24,US,United States of America,AMRO,1,6,0,0
82286,2020-01-25,US,United States of America,AMRO,0,6,0,0
82287,2020-01-26,US,United States of America,AMRO,3,9,0,0
82288,2020-01-27,US,United States of America,AMRO,0,9,0,0
82289,2020-01-28,US,United States of America,AMRO,0,9,0,0
82290,2020-01-29,US,United States of America,AMRO,0,9,0,0
82291,2020-01-30,US,United States of America,AMRO,1,10,0,0
82292,2020-01-31,US,United States of America,AMRO,1,11,0,0
82293,2020-02-01,US,United States of America,AMRO,1,12,0,0
...,...,...,...,...,...,...,...,...
82598,2020-12-02,US,United States of America,AMRO,151204,13385755,1235,266043
82599,2020-12-03,US,United States of America,AMRO,177976,13563731,2439,268482
82600,2020-12-04,US,United States of America,AMRO,195769,13759500,2751,271233
82601,2020-12-05,US,United States of America,AMRO,218671,13978171,2844,274077
82602,2020-12-06,US,United States of America,AMRO,213127,14191298,2426,276503
82603,2020-12-07,US,United States of America,AMRO,205837,14397135,2303,278806
82604,2020-12-08,US,United States of America,AMRO,173388,14570523,1107,279913
82605,2020-12-09,US,United States of America,AMRO,185473,14755996,1529,281442
82606,2020-12-10,US,United States of America,AMRO,216360,14972356,2552,283994
82607,2020-12-11,US,United States of America,AMRO,230852,15203208,3390,287384
82608,2020-12-12,US,United States of America,AMRO,201681,15404889,2749,290133
82609,2020-12-13,US,United States of America,AMRO,243209,15648098,2996,293129
82610,2020-12-14,US,United States of America,AMRO,212577,15860675,2277,295406
82611,2020-12-15,US,United States of America,AMRO,180420,16041095,1434,296840
82612,2020-12-16,US,United States of America,AMRO,204281,16245376,1754,298594
82613,2020-12-17,US,United States of America,AMRO,201468,16446844,2942,301536
82614,2020-12-18,US,United States of America,AMRO,235805,16682649,3424,304960
82615,2020-12-19,US,United States of America,AMRO,229915,16912564,3443,308403
82616,2020-12-20,US,United States of America,AMRO,402270,17314834,2747,311150
82617,2020-12-21,US,United States of America,AMRO,200257,17515091,2598,313748
82618,2020-12-22,US,United States of America,AMRO,197199,17712290,1570,315318
82619,2020-12-23,US,United States of America,AMRO,182819,17895109,1714,317032
82620,2020-12-24,US,United States of America,AMRO,195151,18090260,3148,320180
82621,2020-12-25,US,United States of America,AMRO,221145,18311405,3347,323527
82622,2020-12-26,US,United States of America,AMRO,192095,18503500,2795,326322
82623,2020-12-27,US,United States of America,AMRO,145489,18648989,1692,328014
82624,2020-12-28,US,United States of America,AMRO,178311,18827300,1296,329310
82625,2020-12-29,US,United States of America,AMRO,145513,18972813,1334,330644
82626,2020-12-30,US,United States of America,AMRO,174814,19147627,1779,332423
82627,2020-12-31,US,United States of America,AMRO,199163,19346790,3366,335789

In [12]:
#jodi amra shorto diye kono dekhte chai
df[df.New_deaths>1000]

,Date_reported,Country_code,Country,WHO_region,New_cases,Cumulative_cases,New_deaths,Cumulative_deaths
3186,2020-10-03,AR,Argentina,AMRO,14001,765002,3351,20288
8985,2020-09-08,BO,Bolivia (Plurinational State of),AMRO,528,120769,1610,7008
10331,2020-05-21,BR,Brazil,AMRO,17408,271628,1179,17971
10333,2020-05-23,BR,Brazil,AMRO,18508,310087,1188,20047
10334,2020-05-24,BR,Brazil,AMRO,20803,330890,1001,21048
10338,2020-05-28,BR,Brazil,AMRO,16324,391222,1039,24512
10339,2020-05-29,BR,Brazil,AMRO,20599,411821,1086,25598
10340,2020-05-30,BR,Brazil,AMRO,26417,438238,1156,26754
10341,2020-05-31,BR,Brazil,AMRO,26928,465166,1124,27878
10345,2020-06-04,BR,Brazil,AMRO,28936,555383,1262,31199
10346,2020-06-05,BR,Brazil,AMRO,28633,584016,1349,32548
10347,2020-06-06,BR,Brazil,AMRO,30925,614941,1473,34021
10348,2020-06-07,BR,Brazil,AMRO,30830,645771,1005,35026
10352,2020-06-11,BR,Brazil,AMRO,32091,739503,1272,38406
10353,2020-06-12,BR,Brazil,AMRO,32913,772416,1274,39680
10354,2020-06-13,BR,Brazil,AMRO,30412,802828,1239,40919
10359,2020-06-18,BR,Brazil,AMRO,34918,923189,1282,45241
10360,2020-06-19,BR,Brazil,AMRO,32188,955377,1269,46510
10361,2020-06-20,BR,Brazil,AMRO,22765,978142,1238,47748
10362,2020-06-21,BR,Brazil,AMRO,54771,1032913,1206,48954
10363,2020-06-22,BR,Brazil,AMRO,34666,1067579,1022,49976
10366,2020-06-25,BR,Brazil,AMRO,39436,1145906,1374,52645
10367,2020-06-26,BR,Brazil,AMRO,42725,1188631,1185,53830
10368,2020-06-27,BR,Brazil,AMRO,39483,1228114,1141,54971
10370,2020-06-29,BR,Brazil,AMRO,38693,1313667,1109,57070
10373,2020-07-02,BR,Brazil,AMRO,33846,1402041,1280,59594
10374,2020-07-03,BR,Brazil,AMRO,46712,1448753,1038,60632
10375,2020-07-04,BR,Brazil,AMRO,48105,1496858,1252,61884
10376,2020-07-05,BR,Brazil,AMRO,42223,1539081,1290,63174
10377,2020-07-06,BR,Brazil,AMRO,37923,1577004,1091,64265
...,...,...,...,...,...,...,...,...
82598,2020-12-02,US,United States of America,AMRO,151204,13385755,1235,266043
82599,2020-12-03,US,United States of America,AMRO,177976,13563731,2439,268482
82600,2020-12-04,US,United States of America,AMRO,195769,13759500,2751,271233
82601,2020-12-05,US,United States of America,AMRO,218671,13978171,2844,274077
82602,2020-12-06,US,United States of America,AMRO,213127,14191298,2426,276503
82603,2020-12-07,US,United States of America,AMRO,205837,14397135,2303,278806
82604,2020-12-08,US,United States of America,AMRO,173388,14570523,1107,279913
82605,2020-12-09,US,United States of America,AMRO,185473,14755996,1529,281442
82606,2020-12-10,US,United States of America,AMRO,216360,14972356,2552,283994
82607,2020-12-11,US,United States of America,AMRO,230852,15203208,3390,287384
82608,2020-12-12,US,United States of America,AMRO,201681,15404889,2749,290133
82609,2020-12-13,US,United States of America,AMRO,243209,15648098,2996,293129
82610,2020-12-14,US,United States of America,AMRO,212577,15860675,2277,295406
82611,2020-12-15,US,United States of America,AMRO,180420,16041095,1434,296840
82612,2020-12-16,US,United States of America,AMRO,204281,16245376,1754,298594
82613,2020-12-17,US,United States of America,AMRO,201468,16446844,2942,301536
82614,2020-12-18,US,United States of America,AMRO,235805,16682649,3424,304960
82615,2020-12-19,US,United States of America,AMRO,229915,16912564,3443,308403
82616,2020-12-20,US,United States of America,AMRO,402270,17314834,2747,311150
82617,2020-12-21,US,United States of America,AMRO,200257,17515091,2598,313748
82618,2020-12-22,US,United States of America,AMRO,197199,17712290,1570,315318
82619,2020-12-23,US,United States of America,AMRO,182819,17895109,1714,317032
82620,2020-12-24,US,United States of America,AMRO,195151,18090260,3148,320180
82621,2020-12-25,US,United States of America,AMRO,221145,18311405,3347,323527
82622,2020-12-26,US,United States of America,AMRO,192095,18503500,2795,326322
82623,2020-12-27,US,United States of America,AMRO,145489,18648989,1692,328014
82624,2020-12-28,US,United States of America,AMRO,178311,18827300,1296,329310
82625,2020-12-29,US,United States of America,AMRO,145513,18972813,1334,330644
82626,2020-12-30,US,United States of America,AMRO,174814,19147627,1779,332423
82627,2020-12-31,US,United States of America,AMRO,199163,19346790,3366,335789

In [13]:
df.loc[df.New_deaths>1000, ["New_deaths", "Country"]]

       New_deaths                           Country
3186         3351                         Argentina
8985         1610  Bolivia (Plurinational State of)
10331        1179                            Brazil
10333        1188                            Brazil
10334        1001                            Brazil
10338        1039                            Brazil
10339        1086                            Brazil
10340        1156                            Brazil
10341        1124                            Brazil
10345        1262                            Brazil
10346        1349                            Brazil
10347        1473                            Brazil
10348        1005                            Brazil
10352        1272                            Brazil
10353        1274                            Brazil
10354        1239                            Brazil
10359        1282                            Brazil
10360        1269                            Brazil
10361        1238                            Brazil
10362        1206                            Brazil
10363        1022                            Brazil
10366        1374                            Brazil
10367        1185                            Brazil
10368        1141                            Brazil
10370        1109                            Brazil
10373        1280                            Brazil
10374        1038                            Brazil
10375        1252                            Brazil
10376        1290                            Brazil
10377        1091                            Brazil
...           ...                               ...
82598        1235          United States of America
82599        2439          United States of America
82600        2751          United States of America
82601        2844          United States of America
82602        2426          United States of America
82603        2303          United States of America
82604        1107          United States of America
82605        1529          United States of America
82606        2552          United States of America
82607        3390          United States of America
82608        2749          United States of America
82609        2996          United States of America
82610        2277          United States of America
82611        1434          United States of America
82612        1754          United States of America
82613        2942          United States of America
82614        3424          United States of America
82615        3443          United States of America
82616        2747          United States of America
82617        2598          United States of America
82618        1570          United States of America
82619        1714          United States of America
82620        3148          United States of America
82621        3347          United States of America
82622        2795          United States of America
82623        1692          United States of America
82624        1296          United States of America
82625        1334          United States of America
82626        1779          United States of America
82627        3366          United States of America

[284 rows x 2 columns]

In [15]:
df.loc[df.Country_code=="US", ["New_cases"]].max()

New_cases    402270
dtype: int64

In [16]:
df.loc[df.Country_code=="US", ["New_cases"]].sum()

New_cases    19346790
dtype: int64

In [17]:
df.New_deaths.idxmax()

82369

In [18]:
df.loc[df.New_deaths.idxmax(),["Date_reported", "Country", "New_cases"]]

Date_reported                  2020-04-17
Country          United States of America
New_cases                           28711
Name: 82369, dtype: object

In [19]:
df[df.New_deaths<0]

,Date_reported,Country_code,Country,WHO_region,New_cases,Cumulative_cases,New_deaths,Cumulative_deaths
942,2020-08-04,DZ,Algeria,AFRO,507,31972,-2,1229
2096,2020-10-05,AO,Angola,AFRO,0,5370,-4,185
4157,2020-06-04,AU,Australia,WPRO,8,7229,-1,102
5336,2020-08-30,BS,Bahamas,AMRO,37,2057,-10,40
11840,2020-07-13,BF,Burkina Faso,AFRO,13,1033,-1,53
16538,2020-06-09,CG,Congo,AFRO,0,683,-2,20
18425,2020-08-15,CU,Cuba,AMRO,55,3229,-1,88
19476,2020-07-05,CZ,Czechia,EURO,121,12440,-1,351
19477,2020-07-06,CZ,Czechia,EURO,75,12515,-3,348
20515,2020-05-13,DK,Denmark,EURO,78,10591,-6,527
23658,2020-12-30,ER,Eritrea,AFRO,181,1220,-1,1
24264,2020-08-30,SZ,Eswatini,AFRO,49,4510,-2,91
26409,2020-07-22,FR,France,EURO,454,166511,-1,30053
26453,2020-09-04,FR,France,EURO,6799,283265,-3,30536
26454,2020-09-05,FR,France,EURO,8860,292125,-1,30535
30761,2020-07-06,GP,Guadeloupe,AMRO,0,184,-2,14
31427,2020-05-05,GT,Guatemala,AMRO,15,703,-2,17
32215,2020-07-04,GN,Guinea,AFRO,71,5521,-13,33
36674,2020-10-03,IE,Ireland,EURO,466,37063,-5,1801
37666,2020-06-25,IT,Italy,EURO,577,239410,-31,34644
48577,2020-06-16,YT,Mayotte,AFRO,28,2310,-1,28
52302,2020-09-09,NaN,Namibia,AFRO,118,8928,-2,89
61639,2020-05-05,PR,Puerto Rico,AMRO,35,1843,-43,54
63207,2020-08-25,RE,Réunion,AFRO,35,1244,-4,2
68196,2020-05-10,ST,Sao Tome and Principe,AFRO,-43,165,-1,4
73305,2020-05-23,SS,South Sudan,AFRO,0,473,-1,5
73415,2020-09-10,SS,South Sudan,AFRO,0,2555,-1,48
73502,2020-12-06,SS,South Sudan,AFRO,12,3166,-1,61
82387,2020-05-05,US,United States of America,AMRO,29266,1154985,-514,67279
86082,2020-06-29,ZW,Zimbabwe,AFRO,0,567,-1,6

In [23]:
#New column toiri kora 
df["pct_cases"]=(df["New_cases"]/df["Cumulative_cases"])*100
df

,Date_reported,Country_code,Country,WHO_region,New_cases,Cumulative_cases,New_deaths,Cumulative_deaths,pct_cases
0,2020-01-03,AF,Afghanistan,EMRO,0,0,0,0,NaN
1,2020-01-04,AF,Afghanistan,EMRO,0,0,0,0,NaN
2,2020-01-05,AF,Afghanistan,EMRO,0,0,0,0,NaN
3,2020-01-06,AF,Afghanistan,EMRO,0,0,0,0,NaN
4,2020-01-07,AF,Afghanistan,EMRO,0,0,0,0,NaN
5,2020-01-08,AF,Afghanistan,EMRO,0,0,0,0,NaN
6,2020-01-09,AF,Afghanistan,EMRO,0,0,0,0,NaN
7,2020-01-10,AF,Afghanistan,EMRO,0,0,0,0,NaN
8,2020-01-11,AF,Afghanistan,EMRO,0,0,0,0,NaN
9,2020-01-12,AF,Afghanistan,EMRO,0,0,0,0,NaN
10,2020-01-13,AF,Afghanistan,EMRO,0,0,0,0,NaN
11,2020-01-14,AF,Afghanistan,EMRO,0,0,0,0,NaN
12,2020-01-15,AF,Afghanistan,EMRO,0,0,0,0,NaN
13,2020-01-16,AF,Afghanistan,EMRO,0,0,0,0,NaN
14,2020-01-17,AF,Afghanistan,EMRO,0,0,0,0,NaN
15,2020-01-18,AF,Afghanistan,EMRO,0,0,0,0,NaN
16,2020-01-19,AF,Afghanistan,EMRO,0,0,0,0,NaN
17,2020-01-20,AF,Afghanistan,EMRO,0,0,0,0,NaN
18,2020-01-21,AF,Afghanistan,EMRO,0,0,0,0,NaN
19,2020-01-22,AF,Afghanistan,EMRO,0,0,0,0,NaN
20,2020-01-23,AF,Afghanistan,EMRO,0,0,0,0,NaN
21,2020-01-24,AF,Afghanistan,EMRO,0,0,0,0,NaN
22,2020-01-25,AF,Afghanistan,EMRO,0,0,0,0,NaN
23,2020-01-26,AF,Afghanistan,EMRO,0,0,0,0,NaN
24,2020-01-27,AF,Afghanistan,EMRO,0,0,0,0,NaN
25,2020-01-28,AF,Afghanistan,EMRO,0,0,0,0,NaN
26,2020-01-29,AF,Afghanistan,EMRO,0,0,0,0,NaN
27,2020-01-30,AF,Afghanistan,EMRO,0,0,0,0,NaN
28,2020-01-31,AF,Afghanistan,EMRO,0,0,0,0,NaN
29,2020-02-01,AF,Afghanistan,EMRO,0,0,0,0,NaN
...,...,...,...,...,...,...,...,...,...
86238,2020-12-02,ZW,Zimbabwe,AFRO,95,10129,0,277,0.937901
86239,2020-12-03,ZW,Zimbabwe,AFRO,114,10243,0,277,1.112955
86240,2020-12-04,ZW,Zimbabwe,AFRO,181,10424,3,280,1.736378
86241,2020-12-05,ZW,Zimbabwe,AFRO,123,10547,1,281,1.166208
86242,2020-12-06,ZW,Zimbabwe,AFRO,70,10617,10,291,0.659320
86243,2020-12-07,ZW,Zimbabwe,AFRO,101,10718,0,291,0.942340
86244,2020-12-08,ZW,Zimbabwe,AFRO,121,10839,3,294,1.116339
86245,2020-12-09,ZW,Zimbabwe,AFRO,0,10839,0,294,0.000000
86246,2020-12-10,ZW,Zimbabwe,AFRO,168,11007,10,304,1.526301
86247,2020-12-11,ZW,Zimbabwe,AFRO,74,11081,1,305,0.667810
86248,2020-12-12,ZW,Zimbabwe,AFRO,0,11081,0,305,0.000000
86249,2020-12-13,ZW,Zimbabwe,AFRO,0,11081,0,305,0.000000
86250,2020-12-14,ZW,Zimbabwe,AFRO,165,11246,2,307,1.467188
86251,2020-12-15,ZW,Zimbabwe,AFRO,112,11358,2,309,0.986089
86252,2020-12-16,ZW,Zimbabwe,AFRO,164,11522,1,310,1.423364
86253,2020-12-17,ZW,Zimbabwe,AFRO,0,11522,0,310,0.000000
86254,2020-12-18,ZW,Zimbabwe,AFRO,344,11866,4,314,2.899039
86255,2020-12-19,ZW,Zimbabwe,AFRO,181,12047,2,316,1.502449
86256,2020-12-20,ZW,Zimbabwe,AFRO,104,12151,2,318,0.855897
86257,2020-12-21,ZW,Zimbabwe,AFRO,174,12325,2,320,1.411765
86258,2020-12-22,ZW,Zimbabwe,AFRO,97,12422,2,322,0.780873
86259,2020-12-23,ZW,Zimbabwe,AFRO,122,12544,4,326,0.972577
86260,2020-12-24,ZW,Zimbabwe,AFRO,0,12544,0,326,0.000000
86261,2020-12-25,ZW,Zimbabwe,AFRO,242,12786,13,339,1.892695
86262,2020-12-26,ZW,Zimbabwe,AFRO,94,12880,2,341,0.729814
86263,2020-12-27,ZW,Zimbabwe,AFRO,83,12963,0,341,0.640284
86264,2020-12-28,ZW,Zimbabwe,AFRO,0,12963,0,341,0.000000
86265,2020-12-29,ZW,Zimbabwe,AFRO,185,13148,13,354,1.407058
86266,2020-12-30,ZW,Zimbabwe,AFRO,0,13148,0,354,0.000000
86267,2020-12-31,ZW,Zimbabwe,AFRO,477,13625,6,360,3.500917